name: Build LaTeX document
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
            root_file: test.tex
            working_directory: Lists/
      - name: Upload
        uses: actions/upload-artifact@master
        with:
            name: Documents
            path: .pdf/**/*.pdf