name: Build LaTeX document
on: [push]
jobs:
    build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
            with:
                root_file: list01.tex
                working_directory: Lists/
      - name: Upload
        uses: actions/upload-artifact@master
            with:
                name: Lists
                path: Lists